Updated all config templates based upon lolh files

diff --git a/rc/bash_profile b/rc/bash_profile
--- a/rc/bash_profile
+++ b/rc/bash_profile
@@ -1,81 +1,87 @@
-# -*- mode: sh -*-
+# -*- MODE: SH -*-
 
-# Bash Profile Template
-# 2018-11-04T14:30
+# TEMPLATE: ~/.bash_profile
+# MODIFED: 2018-11-05T12:00
 
-
-
-
-###############
-### USER'S PS1
-###############
-printf "\n${YELLOW}[changing PS1]${CLEAR}\n"
-echo "from --> $PS1"
-
-export PS1="${WHITEBOLD}>>>${YELLOWBOLD}[\!]${CYANBOLD}\u:\h${BLUEBOLD} \w \e${CLEAR}\n?"
-# export PS1="\e[38;5;225m>>>\e[38;5;87m[\!]\e[33;1m\u:\h\e[38;5;39m \d \A\e[38;5;10m \w\e[0m\n?"
-
-echo "to   --> $PS1"
-
-# I think these can be used inside a prompt...
-# ϟ ☭ Ѫ ൿ ൠ ඞ ෴ ஃ ৯ ॐ Ճ ҂ Ω Δ π ʃ ɐ Ɣ ƒ Ŀ Ħ × ¿ ∑ ∀ ∃ ∄ ∞ ∫ ∮ ∬ ∨∧ ∻ ∴ ∵ ≠ ⊕ ⊗ ⊢ ⊣
-# ♅ ♆ ♡ ♥ ⚒ ⚙ ⚛ ✾ ❉ ❯ ❳ ➙ ➤ ➳ ➺ ➻ ⟗ ⟞ ⟢ ⟫ ⟶ ⟹ ⟿ 𐄡 𐄨 𐅍 𐌈 𐌎 𐌇 𐐝 𝄞 𝄢 𝄆 ᐉ ᗚ ᕯ Ꮬ ⊶ ⊾
-# ⊿ ⋈ ⋊ ⋗ ⊙ ⊚ ≣ ░ ▓ ▞ ▣ ◈ ◉ ☠ ☢ ☣ ☬ ៚
+# User's .bash_profile
+################################################################################
 
 
-#################
-### USER'S EMACS
-#################
+
+
+################################################################################
+### USER'S Emacs Environment Variables
+
+## The directory used by Emacs to hold the server sockets appears to vary wildly
+## between systems and builds and must be checked.  The directory is revealed by
+## Emacs when you do a '(server-force-delete)'.
+
 export EMACS_HOME=${HOME}/.emacs.d
 export EMACS_INIT=init.el
 export EMACS_WIDTH=250
 export TERMSERVER=termserver
-## The server directory locations and names really seem completely system
-## dependent and on how emacs and Emacs.app have been compiled and set up
-
-# export EMACS_SERVER_DIR=/usr/local/dev/tmp/emacs501 # <-- lolh
-export EMACS_SERVER_DIR=/var/folders/x_ # /.../emacs501 <-- pine
+# export EMACS_SERVER_DIR=/usr/local/dev/tmp/emacs501   # <-- lolh
+# export EMACS_SERVER_DIR=/var/folders/x_ # /.../emacs501 <-- pine
+################################################################################
 
 
-###########################
-### EMACS SERVER FUNCTIONS
-###########################
+
+
+################################################################################
+### Emacs server functions
+
+##    termserver()    : start and stop the terminal daemon
+##    guiserver()     : start and stop the GUI server
+##    emacsservers()  : start and stop both
+##    show_guiserver():helper function
+
 termserver() {
-    # The terminal server runs as a daemon; look for daemon=termserver as a running process
+    # The terminal server runs as a daemon; to determine whether a daemon is
+    # currently running, look for daemon=termserver as a process using 'pgrep';
+    # to kill the daemon, kill the process; force-deleting the server in emacs
+    # breaks the connection with the process, but leaves the process running;
+    # starting a new daemon thereafter just accumulates processes.
+    # Execute this function from ~/.bashrc with --start option to always have a
+    # running terminal server (or use emacsserver --startall).
 
+    # --------------------------------------------------------------------------
     # USAGE: termserver [ --start | --kill ]
-    # without any options, display status and exit
-    # execute this function from bashrc with --start option to always have a running daemon
+    #        without any options, display status and exit
+    # --------------------------------------------------------------------------
 
     termserver=$(pgrep -f termserver)
     if [ $termserver ]
     then
-	echo Found a running termserver:
+	printf "${YELLOW}Found a running termserver:${WHITEBOLD}\n"
 	echo ---------------------------------------------------------------------------
 	ps -f $termserver
 	echo ---------------------------------------------------------------------------
 	if [[ $1 == --kill ]]
 	then
-	    echo -n Killing termserver...
-	    pkill -f termserver && echo killed || echo not killed
+	    printf "${BLUE}Killing termserver..."
+	    pkill -f termserver && \
+		printf "${GREEN}killed${CLEAR}\n" || \
+		printf "${BLINK}${F_RED}not killed${CLEAR}\n"
 	fi
 	echo
 	
     else
-	echo Did not find a running termserver.
+	printf "${YELLOW}Did not find a running termserver.${CLEAR}\n"
 	if [[ $1 == --start ]]
 	then
+	    printf "${BLUE}starting termserver...${CLEAR}"
 	    emacs --bg-daemon=${TERMSERVER}
 	    [ $(pgrep -f ${TERMSERVER}) ] && \
-		echo started || \
-		    echo failed to start
+		printf "${GREEN}started${WHITEBOLD}\n" || \
+		printf "${BLINK}${F_RED}failed to start${CLEAR}\n"
 	    echo ---------------------------------------------------------------------------
 	    ps -f $(pgrep -f ${TERMSERVER})
 	    echo ---------------------------------------------------------------------------
-	    echo
+	    printf "${CLEAR}\n"
 	fi
     fi
-}
+} # END termserver()
+
 
 guiserver() {
     # The  Emacs  GUI  server  establishes  a  socket  in  a  temporary  folder
@@ -87,44 +93,54 @@ guiserver() {
     # (server-start).  To kill the server,  invoke emacsclient with the command
     # (save-buffers-kill-terminal).
 
-    printf "${WHITEBOLD}"
     if [ $(find ${EMACS_SERVER_DIR} -path \*/emacs501/server 2>/dev/null) ]
     then
-	echo Found a running guiserver.
+	printf "${YELLOW}Found a running guiserver.${WHITEBOLD}\n"
 	echo ---------------------------------------------------------------------------
 	show_guiserver
 	echo ---------------------------------------------------------------------------
+
 	if [[ $1 == --kill ]]
 	then
-	    echo -n Killing gui server...
-	    emacsclient -s server --eval '(save-buffers-kill-terminal 0)' && echo killed || echo not killed
+	    printf "${BLUE}Killing gui server..."
+	    emacsclient -s server --eval '(save-buffers-kill-terminal 0)' && \
+		printf "${GREEN}killed${CLEAR}\n" || \
+		printf "${BLINK}${F_RED}not killed${CLEAR}\n"
 	fi
+	echo
 	
     else
-	echo Did not find a running guiserver.
+	printf "${YELLOW}Did not find a running guiserver.${CLEAR}\n"
 	if [[ $1 == --start ]]
 	then
-	    echo -n Starting gui server...
-	    open -jb org.gnu.Emacs --args --eval '(server-start)' && echo started || echo not started
+	    printf "${BLUE}Starting gui server...${CLEAR}"
+	    open -jb org.gnu.Emacs --args --eval '(server-start)' && \
+		printf "${GREEN}started${CLEAR}\n" || \
+	        printf "${BLINK}${F_RED}not started${CLEAR}\n"
+	    printf "${WHITEBOLD}"
 	    echo ---------------------------------------------------------------------------
 	    show_guiserver
 	    echo ---------------------------------------------------------------------------
 	fi
     fi
     printf "${CLEAR}"
-}
+} # END guiserver()
 
 
 emacsservers() {
     # This is  a wrapper  function for  the termserver  and the  guiserver.  It
     # starts and kills both with a single command.
+
+    # --------------------------------------------------------------------------
+    # USAGE: emacsservers --status | --startall | --killall | -h | --help
+    #---------------------------------------------------------------------------
     
     printf "${WHITEBOLD}"
     case $1 in
 	--status)    { termserver; guiserver; } ;;
 	--startall)  { termserver --start; guiserver --start; } ;;
 	--killall)   { termserver --kill; guiserver --kill; } ;;
-	--help)      {
+	--help|-h)   {
 	    echo ===============================================================================
 	    echo \'ecg FILE \&\' runs \'emacsclient FILE \&\' using the EmacsMac server \'server\'
 	    echo \'ect FILE\' runs \'emacsclient FILE\' using the terminal emacs server \'termserver\'
@@ -136,7 +152,7 @@ emacsservers() {
 	*) echo Ignoring unrecognized option `$1` ;;
     esac
     printf "${CLEAR}"
-}
+} # END emacsservers()
 
 
 show_guiserver() {
@@ -146,21 +162,59 @@ show_guiserver() {
 	sed -n \
 	    -e '1p' \
 	    -e '2 s|'${EMACS_SERVER_DIR}'.*Emacs|'${EMACS_SERVER_DIR}'/...Emacs|p'
-}
+} # END show_guiserver()
 
+
+ecg() {
+    # function to run the GUI server with emacsclient and arguments in the
+    # background with '&'
+
+    emacsclient -qs server "$@" &
+} # END ecg()
+
+################################################################################
+
+
+
+
+################################################################################
+### Edit Emacs' Init File
 
 initEmacs() {
     # TODO: reinitialize when done
     emacs -Q ${EMACS_HOME}/${EMACS_INIT}
-}
+} # END 
+################################################################################
 
 
-### shortcuts for invoking emacsclient for both termserver and guiserver
-### TODO set up alternate editor functionality
-alias ect='emacsclient -qs termserver'
-ecg() {
-    emacsclient -s server "$@" &
-}
+
+
+################################################################################
+### USER'S OPAM CONFIGURATION
+
+printf "\n${YELLOW}[opam configuration...${CYANBOLD}/Users/pine/.opam/opam-init/init.sh]${CLEAR}\n"
+
+test -r /Users/pine/.opam/opam-init/init.sh && \
+    . /Users/pine/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
+
+printf "${YELLOW}[...opam configuration]${CLEAR}\n"
+################################################################################
+
+
+
+
+
+################################################################################
+### Source ~/.bashrc
+
+printf "\n${YELLOW}[${CYANBOLD}~/.bashrc...${YELLOW}]${CLEAR}\n"
+
+[[ -s ~/.bashrc ]] && source ~/.bashrc
+
+printf "${YELLOW}[${CYANBOLD}... ~/.bashrc${YELLOW}]${CLEAR}\n"
+################################################################################
+
+
 
 
 ################
@@ -176,13 +230,7 @@ NEW_PATH=$(new_path_marker ${OLD_PATH} ${PATH})
 printf "${YELLOW}[new path: ${NEW_PATH}]\n"
 
 
-########################
-### SYSTEM-WIDE ALIASES
-########################
-alias ls='ls -FG'
-alias lsl='ls -lAFG'
-#alias lsl='ls -lh'
-alias lsd='lsl | grep ^d | sed -Ee s/^.*\(\[\ \]\)\(\[^\ \]*\)$/\\2/'
+
 
 ####################
 ### USER'S PERLBREW
@@ -194,21 +242,11 @@ source ~/perl5/perlbrew/etc/bashrc
 printf "${YELLOW}[...${CYANBOLD}~/perl5/perlbrew/etc/bashrc${YELLOW}]${CLEAR}\n"
 
 
-##############################
-### USER'S OPAM CONFIGURATION
-##############################
 
-printf "\n${YELLOW}[opam configuration...${CYANBOLD}/Users/pine/.opam/opam-init/init.sh]${CLEAR}\n"
 
-test -r /Users/pine/.opam/opam-init/init.sh && . /Users/pine/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
 
-printf "${YELLOW}[...opam configuration]${CLEAR}\n"
 
-printf "\n${YELLOW}[${CYANBOLD}~/.bashrc...${YELLOW}]${CLEAR}\n"
 
-[[ -s ~/.bashrc ]] && source ~/.bashrc
-
-printf "${YELLOW}[${CYANBOLD}... ~/.bashrc${YELLOW}]${CLEAR}\n"
 
 
 ### HOMEBREW OPENSSL NOTES
